on:
  schedule:
    - cron: "* */1 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    name: Workflow test
    steps:
      - name: Start workflow
        id: test
        uses: monun-docs/auto-contrib@v1.0
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          repo: monun-docs/auto-contrib